version: '3'

services:
  web:
    container_name: 'tibberrobot'
    image: 'tibberrobot'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/tibberrobot
    ports:
      - '5001:80'
    depends_on:
      - 'db'
    networks:
      - aspnetcoreapp-network

  postgresql_database: 
    image: postgres:latest
    environment:
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=abuzafor73azf
        - POSTGRES_DB=tibberrobot
    ports:
        - "5432:5432"
    restart: unless-stopped
    volumes: 
        - database-data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      environment:
          - PGADMIN_DEFAULT_EMAIL=rakel@logi-uas.com
          - PGADMIN_DEFAULT_PASSWORD=admin
      ports: 
        - "5050:80"
      restart: unless-stopped
      volumes: 
            - pgadmin:/root/.pgadmin
  
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=abuzafor73azf
    networks:
      - aspnetcoreapp-network

volumes: 
    database-data:
    pgadmin: 

networks:
  aspnetcoreapp-network:
    driver: bridge